[package]
name = "mc-link-compat"
version = "0.1.0"
edition = "2024"

[dependencies]
mc-link-core = { path = "../mc-link-core" }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = "1.0"
toml = { workspace = true }
zip = "2.1"